-- ============================================================================
-- V3 — Quartz JDBC JobStore 表结构
--
-- 来源：org/quartz/impl/jdbcjobstore/tables_mysql_innodb.sql（Quartz 2.3.2 官方脚本），
--       为纳入 Flyway 单一事实源而内联，并做了三处必要调整：
--         1) 去掉 DROP TABLE 语句 —— 生产迁移脚本不允许销毁数据；
--         2) 所有 CREATE TABLE / CREATE INDEX 改为 IF NOT EXISTS —— 全新库与旧库均可安全执行；
--         3) 表与列补上中文 COMMENT，便于运维直接读库。
--       application.yml 中 spring.quartz.jdbc.initialize-schema 设为 never，
--       避免 Boot 内置脚本与 Flyway 争抢同一批表。
-- ============================================================================

CREATE TABLE IF NOT EXISTS QRTZ_JOB_DETAILS (
    SCHED_NAME        VARCHAR(120) NOT NULL COMMENT '调度器名称',
    JOB_NAME          VARCHAR(190) NOT NULL COMMENT '作业名称',
    JOB_GROUP         VARCHAR(190) NOT NULL COMMENT '作业分组',
    DESCRIPTION       VARCHAR(250) NULL COMMENT '描述',
    JOB_CLASS_NAME    VARCHAR(250) NOT NULL COMMENT '作业实现类',
    IS_DURABLE        VARCHAR(1)   NOT NULL COMMENT '是否持久化',
    IS_NONCONCURRENT  VARCHAR(1)   NOT NULL COMMENT '是否禁止并发',
    IS_UPDATE_DATA    VARCHAR(1)   NOT NULL COMMENT '是否更新 JobDataMap',
    REQUESTS_RECOVERY VARCHAR(1)   NOT NULL COMMENT '是否需要恢复',
    JOB_DATA          BLOB         NULL COMMENT '作业数据',
    PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'Quartz 作业明细';

CREATE TABLE IF NOT EXISTS QRTZ_TRIGGERS (
    SCHED_NAME     VARCHAR(120) NOT NULL COMMENT '调度器名称',
    TRIGGER_NAME   VARCHAR(190) NOT NULL COMMENT '触发器名称',
    TRIGGER_GROUP  VARCHAR(190) NOT NULL COMMENT '触发器分组',
    JOB_NAME       VARCHAR(190) NOT NULL COMMENT '作业名称',
    JOB_GROUP      VARCHAR(190) NOT NULL COMMENT '作业分组',
    DESCRIPTION    VARCHAR(250) NULL COMMENT '描述',
    NEXT_FIRE_TIME BIGINT(13)   NULL COMMENT '下次触发时间（毫秒）',
    PREV_FIRE_TIME BIGINT(13)   NULL COMMENT '上次触发时间（毫秒）',
    PRIORITY       INT          NULL COMMENT '优先级',
    TRIGGER_STATE  VARCHAR(16)  NOT NULL COMMENT '触发器状态',
    TRIGGER_TYPE   VARCHAR(8)   NOT NULL COMMENT '触发器类型',
    START_TIME     BIGINT(13)   NOT NULL COMMENT '生效起始时间（毫秒）',
    END_TIME       BIGINT(13)   NULL COMMENT '生效结束时间（毫秒）',
    CALENDAR_NAME  VARCHAR(190) NULL COMMENT '日历名称',
    MISFIRE_INSTR  SMALLINT(2)  NULL COMMENT 'misfire 处理策略',
    JOB_DATA       BLOB         NULL COMMENT '作业数据',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    KEY IDX_QRTZ_T_J (SCHED_NAME, JOB_NAME, JOB_GROUP),
    KEY IDX_QRTZ_T_JG (SCHED_NAME, JOB_GROUP),
    KEY IDX_QRTZ_T_C (SCHED_NAME, CALENDAR_NAME),
    KEY IDX_QRTZ_T_G (SCHED_NAME, TRIGGER_GROUP),
    KEY IDX_QRTZ_T_STATE (SCHED_NAME, TRIGGER_STATE),
    KEY IDX_QRTZ_T_N_STATE (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE),
    KEY IDX_QRTZ_T_N_G_STATE (SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE),
    KEY IDX_QRTZ_T_NEXT_FIRE_TIME (SCHED_NAME, NEXT_FIRE_TIME),
    KEY IDX_QRTZ_T_NFT_ST (SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME),
    KEY IDX_QRTZ_T_NFT_MISFIRE (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME),
    KEY IDX_QRTZ_T_NFT_ST_MISFIRE (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE),
    KEY IDX_QRTZ_T_NFT_ST_MISFIRE_GRP (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'Quartz 触发器';

CREATE TABLE IF NOT EXISTS QRTZ_SIMPLE_TRIGGERS (
    SCHED_NAME      VARCHAR(120) NOT NULL COMMENT '调度器名称',
    TRIGGER_NAME    VARCHAR(190) NOT NULL COMMENT '触发器名称',
    TRIGGER_GROUP   VARCHAR(190) NOT NULL COMMENT '触发器分组',
    REPEAT_COUNT    BIGINT(7)    NOT NULL COMMENT '重复次数',
    REPEAT_INTERVAL BIGINT(12)   NOT NULL COMMENT '重复间隔（毫秒）',
    TIMES_TRIGGERED BIGINT(10)   NOT NULL COMMENT '已触发次数',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'Quartz 简单触发器';

CREATE TABLE IF NOT EXISTS QRTZ_CRON_TRIGGERS (
    SCHED_NAME      VARCHAR(120) NOT NULL COMMENT '调度器名称',
    TRIGGER_NAME    VARCHAR(190) NOT NULL COMMENT '触发器名称',
    TRIGGER_GROUP   VARCHAR(190) NOT NULL COMMENT '触发器分组',
    CRON_EXPRESSION VARCHAR(120) NOT NULL COMMENT 'Cron 表达式',
    TIME_ZONE_ID    VARCHAR(80)  NULL COMMENT '时区',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'Quartz Cron 触发器';

CREATE TABLE IF NOT EXISTS QRTZ_SIMPROP_TRIGGERS (
    SCHED_NAME    VARCHAR(120) NOT NULL COMMENT '调度器名称',
    TRIGGER_NAME  VARCHAR(190) NOT NULL COMMENT '触发器名称',
    TRIGGER_GROUP VARCHAR(190) NOT NULL COMMENT '触发器分组',
    STR_PROP_1    VARCHAR(512) NULL COMMENT '字符串属性1',
    STR_PROP_2    VARCHAR(512) NULL COMMENT '字符串属性2',
    STR_PROP_3    VARCHAR(512) NULL COMMENT '字符串属性3',
    INT_PROP_1    INT          NULL COMMENT '整型属性1',
    INT_PROP_2    INT          NULL COMMENT '整型属性2',
    LONG_PROP_1   BIGINT       NULL COMMENT '长整型属性1',
    LONG_PROP_2   BIGINT       NULL COMMENT '长整型属性2',
    DEC_PROP_1    NUMERIC(13,4) NULL COMMENT '小数属性1',
    DEC_PROP_2    NUMERIC(13,4) NULL COMMENT '小数属性2',
    BOOL_PROP_1   VARCHAR(1)   NULL COMMENT '布尔属性1',
    BOOL_PROP_2   VARCHAR(1)   NULL COMMENT '布尔属性2',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'Quartz 扩展属性触发器';

CREATE TABLE IF NOT EXISTS QRTZ_BLOB_TRIGGERS (
    SCHED_NAME    VARCHAR(120) NOT NULL COMMENT '调度器名称',
    TRIGGER_NAME  VARCHAR(190) NOT NULL COMMENT '触发器名称',
    TRIGGER_GROUP VARCHAR(190) NOT NULL COMMENT '触发器分组',
    BLOB_DATA     BLOB         NULL COMMENT '二进制数据',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'Quartz Blob 触发器';

CREATE TABLE IF NOT EXISTS QRTZ_CALENDARS (
    SCHED_NAME    VARCHAR(120) NOT NULL COMMENT '调度器名称',
    CALENDAR_NAME VARCHAR(190) NOT NULL COMMENT '日历名称',
    CALENDAR      BLOB         NOT NULL COMMENT '日历数据',
    PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'Quartz 日历';

CREATE TABLE IF NOT EXISTS QRTZ_PAUSED_TRIGGER_GRPS (
    SCHED_NAME    VARCHAR(120) NOT NULL COMMENT '调度器名称',
    TRIGGER_GROUP VARCHAR(190) NOT NULL COMMENT '触发器分组',
    PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'Quartz 暂停的触发器分组';

CREATE TABLE IF NOT EXISTS QRTZ_FIRED_TRIGGERS (
    SCHED_NAME        VARCHAR(120) NOT NULL COMMENT '调度器名称',
    ENTRY_ID          VARCHAR(95)  NOT NULL COMMENT '触发记录ID',
    TRIGGER_NAME      VARCHAR(190) NOT NULL COMMENT '触发器名称',
    TRIGGER_GROUP     VARCHAR(190) NOT NULL COMMENT '触发器分组',
    INSTANCE_NAME     VARCHAR(190) NOT NULL COMMENT '调度器实例名',
    FIRED_TIME        BIGINT(13)   NOT NULL COMMENT '触发时间（毫秒）',
    SCHED_TIME        BIGINT(13)   NOT NULL COMMENT '计划时间（毫秒）',
    PRIORITY          INT          NOT NULL COMMENT '优先级',
    STATE             VARCHAR(16)  NOT NULL COMMENT '状态',
    JOB_NAME          VARCHAR(190) NULL COMMENT '作业名称',
    JOB_GROUP         VARCHAR(190) NULL COMMENT '作业分组',
    IS_NONCONCURRENT  VARCHAR(1)   NULL COMMENT '是否禁止并发',
    REQUESTS_RECOVERY VARCHAR(1)   NULL COMMENT '是否需要恢复',
    PRIMARY KEY (SCHED_NAME, ENTRY_ID),
    KEY IDX_QRTZ_FT_TRIG_INST_NAME (SCHED_NAME, INSTANCE_NAME),
    KEY IDX_QRTZ_FT_INST_JOB_REQ_RCVRY (SCHED_NAME, INSTANCE_NAME, REQUESTS_RECOVERY),
    KEY IDX_QRTZ_FT_J_G (SCHED_NAME, JOB_NAME, JOB_GROUP),
    KEY IDX_QRTZ_FT_JG (SCHED_NAME, JOB_GROUP),
    KEY IDX_QRTZ_FT_T_G (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    KEY IDX_QRTZ_FT_TG (SCHED_NAME, TRIGGER_GROUP)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'Quartz 已触发记录';

CREATE TABLE IF NOT EXISTS QRTZ_SCHEDULER_STATE (
    SCHED_NAME        VARCHAR(120) NOT NULL COMMENT '调度器名称',
    INSTANCE_NAME     VARCHAR(190) NOT NULL COMMENT '实例名',
    LAST_CHECKIN_TIME BIGINT(13)   NOT NULL COMMENT '最后心跳时间（毫秒）',
    CHECKIN_INTERVAL  BIGINT(13)   NOT NULL COMMENT '心跳间隔（毫秒）',
    PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'Quartz 调度器实例状态';

CREATE TABLE IF NOT EXISTS QRTZ_LOCKS (
    SCHED_NAME VARCHAR(120) NOT NULL COMMENT '调度器名称',
    LOCK_NAME  VARCHAR(40)  NOT NULL COMMENT '锁名称',
    PRIMARY KEY (SCHED_NAME, LOCK_NAME)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = 'Quartz 悲观锁';
